// app/layout.js
import { Geist, Geist_Mono, Titillium_Web } from "next/font/google";
import "./globals.css";
import {
  storyblokInit,
  apiPlugin,
  getStoryblokApi,
} from "@storyblok/react/rsc";
import { StoryblokProvider } from "@/components/StoryblokProvider";
import { Tour } from "../components/Tour";
import { Page } from "@/components/Page";
import { Hero } from "@/components/Hero";
import { Grid } from "@/components/grid";
import { Feature } from "@/components/Feature";
import { Testimonial } from "@/components/Testimonial";
import { RecomendedTours } from "@/components/RecomendedTours";
// NEW: Import the Header and NavLink components
import { Header } from "@/components/Header";
import { NavLink } from "@/components/NavLink";
import ReviewInfo from "@/components/ReviewInfo";
import Carousel from "@/components/Carousel";
import Article from "@/components/Article";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cachedFetch = (input, init) => {
  return fetch(input, {
    ...init,
    cache: process.env.NODE_ENV === "development" ? "no-store" : "force-cache",
  });
};

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Titillium = Titillium_Web({
  variable: "--font-titillium",
  subsets: ["latin"],
  weight: ["300", "400", "600", "900", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  components: {
    tour: Tour,
    page: Page,
    hero: Hero,
    grid: Grid,
    feature: Feature,
    testimonial: Testimonial,
    reccomended_tours: RecomendedTours,
    // NEW: Register the Header and NavLink components
    Header: Header,
    navlinks: NavLink,
    review_info: ReviewInfo,
    carousel: Carousel,
    article: Article,
  },
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
});

// NEW: Function to fetch global content
async function getGlobalNav() {
  const storyblokApi = getStoryblokApi();
  const { data } = await storyblokApi.get("cdn/stories/settings", {
    version: process.env.NODE_ENV === "development" ? "draft" : "published",
  });
  // Assuming the header is the first block in the "Settings" story
  return data?.story?.content?.blocks?.[0];
}

// NEW: Make the layout an async function
export default async function RootLayout({ children }) {
  // NEW: Fetch the header data
  const headerBlok = await getGlobalNav();

  return (
    <html lang="en">
      <body className={`${Titillium.className} antialiased`}>
        {/* NEW: Render the Header if it exists */}
        {headerBlok && <Header blok={headerBlok} />}
        <StoryblokProvider>{children}</StoryblokProvider>
      </body>
    </html>
  );
}
